regex update
jakehlee/JDG-Cogs-V3 pull request #19
Opened 2024-03-19 18:21 UTC by hatchcanon

NYT has added a comma in the output. This PR allows for an optional comma between the digits.

2024-03-21 21:10 UTC, jakehlee requested changes
Thanks for the PR! I stopped playing Wordle so I didn't notice they're past 1,000 wordles now. 

Should the regex have `\d{0,3}` instead of `\d{1,3}` before the comma `,?` to support re-parsing older solves (in the case of `[p]wordlereparse`? I think the current string wouldn't capture, say, `Wordle 906 5/6`

We'll have to re-do this once they pass 1,000,000 Wordles :)

2024-03-21 22:02 UTC, hatchcanon commented
Good point. Didn't factor in re-parsing, only thought ahead

2024-03-21 23:09 UTC, jakehlee approved these changes
LGTM 👍

2024-03-21 23:09 UTC, jakehlee commented
Thank you again!

2024-03-21 23:09 UTC, merged

2024-03-27 13:04 UTC, jakehlee commented
Quick update, I'm now seeing a `ValueError: invalid literal for int() with base 10: '1,012'` - fix incoming in a couple hours.